version: '2'
services:
  redmine:
    build:
      context: .
    #command: rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails server -b 0.0.0.0
    environment:
      RAILS_ENV: development
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: password

    ports:
      - 3000:3000
      - 1234:1234
    volumes:
      - ./volumes/log:/usr/src/redmine/log
      - ../:/usr/src/redmine/plugins/redmine_slack_notifier/
      #- ./redmine_checklists:/usr/src/redmine/plugins/redmine_checklists/
    depends_on:
      - mysql
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.7    
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

